{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {
    "gather": {
     "logged": 1598275788035
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Workspace name: quick-starts-ws-241963\n",
      "Azure region: westeurope\n",
      "Subscription id: 61c5c3f0-6dc7-4ed9-a7f3-c704b20e3b30\n",
      "Resource group: aml-quickstarts-241963\n"
     ]
    }
   ],
   "source": [
    "from azureml.core import Workspace, Experiment\n",
    "\n",
    "ws = Workspace.from_config()\n",
    "exp = Experiment(workspace=ws, name=\"AzureProject\")\n",
    "\n",
    "print('Workspace name: ' + ws.name, \n",
    "      'Azure region: ' + ws.location, \n",
    "      'Subscription id: ' + ws.subscription_id, \n",
    "      'Resource group: ' + ws.resource_group, sep = '\\n')\n",
    "\n",
    "run = exp.start_logging()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {
    "gather": {
     "logged": 1598275788675
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found existing cluster, use it.\n",
      "\n",
      "Running\n",
      "{'errors': [], 'creationTime': '2023-09-28T13:43:21.534368+00:00', 'createdBy': {'userObjectId': '92a5563a-8782-4728-a447-f9eee0fbc083', 'userTenantId': '660b3398-b80e-49d2-bc5b-ac1dc93b5254', 'userName': None}, 'modifiedTime': '2023-09-28T13:48:25.942271+00:00', 'state': 'Running', 'vmSize': 'STANDARD_D2S_V3'}\n"
     ]
    }
   ],
   "source": [
    "from azureml.core.compute import ComputeTarget, AmlCompute\n",
    "from azureml.core.compute_target import ComputeTargetException\n",
    "\n",
    "cpu_cluster_name = \"AzureProject\"\n",
    "\n",
    "# TODO: Create compute cluster\n",
    "# Use vm_size = \" Standard_D2_V2\"in your provisioning configuration.\n",
    "# max_nodes should be no greater than 4.\n",
    "\n",
    "### YOUR CODE HERE ###\n",
    "# verify that cluser does not exist already\n",
    "try:\n",
    "    cpu_cluster=ComputeTarget(workspace=ws, name= cpu_cluster_name)\n",
    "    print(\"Found existing cluster, use it.\")\n",
    "except ComputeTargetException:\n",
    "    compute_config=AmlCompute.provisioning_configuration(vm_size=\"Standard_D2_V2\", max_nodes=4)\n",
    "    cpu_cluster= ComputeTarget.create(ws,cpu_cluster_name,compute_config)\n",
    "\n",
    "cpu_cluster.wait_for_completion(show_output=True)\n",
    "# print detailed status for the current cluster\n",
    "print(cpu_cluster.get_status().serialize())\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {
    "gather": {
     "logged": 1598275789986
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from azureml.widgets import RunDetails\n",
    "from azureml.train.sklearn import SKLearn\n",
    "from azureml.train.hyperdrive.run import PrimaryMetricGoal\n",
    "from azureml.train.hyperdrive.policy import BanditPolicy\n",
    "from azureml.train.hyperdrive.sampling import RandomParameterSampling\n",
    "from azureml.train.hyperdrive.runconfig import HyperDriveConfig\n",
    "from azureml.train.hyperdrive.parameter_expressions import choice, uniform\n",
    "from azureml.core import Environment, ScriptRunConfig\n",
    "import os\n",
    "\n",
    "# Specify parameter sampler\n",
    "ps = RandomParameterSampling(\n",
    "{'--C':choice(0.01,0.1,1,10,50,100,500,1000),\n",
    "'--max_iter':choice(50,100,200,300)})\n",
    "\n",
    "# Specify a Policy\n",
    "policy = BanditPolicy(evaluation_interval=1,slack_factor=0.1)\n",
    "\n",
    "if \"training\" not in os.listdir():\n",
    "    os.mkdir(\"./training\")\n",
    "\n",
    "# Setup environment for your training run\n",
    "sklearn_env = Environment.from_conda_specification(name='sklearn-env', file_path='conda_dependencies.yml')\n",
    "\n",
    "# Create a ScriptRunConfig Object to specify the configuration details of your training job\n",
    "src = ScriptRunConfig(source_directory='.',\n",
    "                     script='train.py',\n",
    "                     compute_target=cpu_cluster,\n",
    "                     environment=sklearn_env)\n",
    "\n",
    "# Create a HyperDriveConfig using the src object, hyperparameter sampler, and policy.\n",
    "hyperdrive_config = HyperDriveConfig(run_config=src,\n",
    "                                    hyperparameter_sampling=ps,\n",
    "                                    policy=policy,\n",
    "                                    primary_metric_name='Accuracy',\n",
    "                                    primary_metric_goal=PrimaryMetricGoal.MAXIMIZE,\n",
    "                                    max_total_runs=16,\n",
    "                                    max_concurrent_runs=4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "aa7f8752a5ab4b54939ec43c4313b205",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "_HyperDriveWidget(widget_settings={'childWidgetDisplay': 'popup', 'send_telemetry': False, 'log_level': 'INFO'â€¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/aml.mini.widget.v1": "{\"status\": \"Failed\", \"workbench_run_details_uri\": \"https://ml.azure.com/runs/HD_2695e6d6-fb22-4f99-b257-cd1444ecb878?wsid=/subscriptions/61c5c3f0-6dc7-4ed9-a7f3-c704b20e3b30/resourcegroups/aml-quickstarts-241963/workspaces/quick-starts-ws-241963&tid=660b3398-b80e-49d2-bc5b-ac1dc93b5254\", \"run_id\": \"HD_2695e6d6-fb22-4f99-b257-cd1444ecb878\", \"run_properties\": {\"run_id\": \"HD_2695e6d6-fb22-4f99-b257-cd1444ecb878\", \"created_utc\": \"2023-09-28T14:48:40.540175Z\", \"properties\": {\"primary_metric_config\": \"{\\\"name\\\":\\\"Accuracy\\\",\\\"goal\\\":\\\"maximize\\\"}\", \"resume_from\": \"null\", \"runTemplate\": \"HyperDrive\", \"azureml.runsource\": \"hyperdrive\", \"platform\": \"AML\", \"ContentSnapshotId\": \"77ac8209-5aa9-499d-9256-12cf909d486a\", \"user_agent\": \"python/3.8.5 (Linux-5.15.0-1040-azure-x86_64-with-glibc2.10) msrest/0.7.1 Hyperdrive.Service/1.0.0 Hyperdrive.SDK/core.1.51.0\", \"space_size\": \"32\"}, \"tags\": {\"_aml_system_max_concurrent_jobs\": \"4\", \"_aml_system_max_total_jobs\": \"16\", \"_aml_system_max_duration_minutes\": \"10080\", \"_aml_system_policy_config\": \"{\\\"name\\\":\\\"Bandit\\\",\\\"properties\\\":{\\\"evaluation_interval\\\":1,\\\"delay_evaluation\\\":0,\\\"slack_factor\\\":0.1}}\", \"_aml_system_generator_config\": \"{\\\"name\\\":\\\"RANDOM\\\",\\\"parameter_space\\\":{\\\"--C\\\":[\\\"choice\\\",[[0.01,0.1,1,10,50,100,500,1000]]],\\\"--max_iter\\\":[\\\"choice\\\",[[50,100,200,300]]]},\\\"properties\\\":null}\", \"_aml_system_primary_metric_config\": \"{\\\"name\\\":\\\"Accuracy\\\",\\\"goal\\\":\\\"maximize\\\"}\", \"_aml_system_platform_config\": \"{\\\"ServiceAddress\\\":\\\"https://westeurope.experiments.azureml.net\\\",\\\"SubscriptionId\\\":\\\"61c5c3f0-6dc7-4ed9-a7f3-c704b20e3b30\\\",\\\"ResourceGroupName\\\":\\\"aml-quickstarts-241963\\\",\\\"WorkspaceName\\\":\\\"quick-starts-ws-241963\\\",\\\"ExperimentName\\\":\\\"AzureProject\\\",\\\"Definition\\\":{\\\"Configuration\\\":null,\\\"Attribution\\\":null,\\\"TelemetryValues\\\":{\\\"amlClientType\\\":\\\"azureml-sdk-train\\\",\\\"amlClientModule\\\":\\\"[Scrubbed]\\\",\\\"amlClientFunction\\\":\\\"[Scrubbed]\\\",\\\"tenantId\\\":\\\"660b3398-b80e-49d2-bc5b-ac1dc93b5254\\\",\\\"amlClientRequestId\\\":\\\"a4e957f6-bc5e-405a-be83-b72a48b661b6\\\",\\\"amlClientSessionId\\\":\\\"4d28af14-0452-4dd9-beb3-59c36890b1cb\\\",\\\"subscriptionId\\\":\\\"61c5c3f0-6dc7-4ed9-a7f3-c704b20e3b30\\\",\\\"estimator\\\":\\\"NoneType\\\",\\\"samplingMethod\\\":\\\"RANDOM\\\",\\\"terminationPolicy\\\":\\\"Bandit\\\",\\\"primaryMetricGoal\\\":\\\"maximize\\\",\\\"maxTotalRuns\\\":16,\\\"maxConcurrentRuns\\\":4,\\\"maxDurationMinutes\\\":10080,\\\"vmSize\\\":null},\\\"Overrides\\\":{\\\"Script\\\":\\\"train.py\\\",\\\"Command\\\":\\\"\\\",\\\"UseAbsolutePath\\\":false,\\\"Arguments\\\":[],\\\"SourceDirectoryDataStore\\\":null,\\\"Framework\\\":0,\\\"Communicator\\\":0,\\\"Target\\\":\\\"AzureProject\\\",\\\"DataReferences\\\":{},\\\"Data\\\":{},\\\"OutputData\\\":{},\\\"Datacaches\\\":[],\\\"JobName\\\":null,\\\"MaxRunDurationSeconds\\\":2592000,\\\"NodeCount\\\":1,\\\"InstanceTypes\\\":[],\\\"Priority\\\":null,\\\"CredentialPassthrough\\\":false,\\\"Identity\\\":null,\\\"Environment\\\":{\\\"Name\\\":\\\"sklearn-env\\\",\\\"AutoRebuild\\\":true,\\\"Python\\\":{\\\"InterpreterPath\\\":\\\"python\\\",\\\"UserManagedDependencies\\\":false,\\\"CondaDependencies\\\":{\\\"dependencies\\\":[\\\"python=3.6.2\\\",\\\"scikit-learn\\\",\\\"numpy\\\",\\\"pandas\\\",{\\\"pip\\\":[\\\"azureml-defaults\\\"]}]},\\\"BaseCondaEnvironment\\\":null},\\\"EnvironmentVariables\\\":{\\\"EXAMPLE_ENV_VAR\\\":\\\"EXAMPLE_VALUE\\\"},\\\"Docker\\\":{\\\"BaseImage\\\":\\\"mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20230509.v1\\\",\\\"Platform\\\":{\\\"Os\\\":\\\"Linux\\\",\\\"Architecture\\\":\\\"amd64\\\"},\\\"BaseDockerfile\\\":null,\\\"BaseImageRegistry\\\":{\\\"Address\\\":null,\\\"Username\\\":null,\\\"Password\\\":null},\\\"Enabled\\\":false,\\\"Arguments\\\":[]},\\\"Spark\\\":{\\\"Repositories\\\":[],\\\"Packages\\\":[],\\\"PrecachePackages\\\":true},\\\"InferencingStackVersion\\\":null},\\\"History\\\":{\\\"OutputCollection\\\":true,\\\"DirectoriesToWatch\\\":[\\\"logs\\\"],\\\"EnableMLflowTracking\\\":true,\\\"snapshotProject\\\":true},\\\"Spark\\\":{\\\"Configuration\\\":{\\\"spark.app.name\\\":\\\"Azure ML Experiment\\\",\\\"spark.yarn.maxAppAttempts\\\":\\\"1\\\"}},\\\"ParallelTask\\\":{\\\"MaxRetriesPerWorker\\\":0,\\\"WorkerCountPerNode\\\":1,\\\"TerminalExitCodes\\\":null,\\\"Configuration\\\":{}},\\\"BatchAi\\\":{\\\"NodeCount\\\":0},\\\"AmlCompute\\\":{\\\"Name\\\":null,\\\"VmSize\\\":null,\\\"RetainCluster\\\":false,\\\"ClusterMaxNodeCount\\\":null},\\\"AISuperComputer\\\":{\\\"InstanceType\\\":\\\"D2\\\",\\\"FrameworkImage\\\":null,\\\"ImageVersion\\\":null,\\\"Location\\\":null,\\\"AISuperComputerStorageData\\\":null,\\\"Interactive\\\":false,\\\"ScalePolicy\\\":null,\\\"VirtualClusterArmId\\\":null,\\\"TensorboardLogDirectory\\\":null,\\\"SSHPublicKey\\\":null,\\\"SSHPublicKeys\\\":null,\\\"EnableAzmlInt\\\":true,\\\"Priority\\\":\\\"Medium\\\",\\\"SLATier\\\":\\\"Standard\\\",\\\"UserAlias\\\":null},\\\"KubernetesCompute\\\":{\\\"InstanceType\\\":null},\\\"Tensorflow\\\":{\\\"WorkerCount\\\":1,\\\"ParameterServerCount\\\":1},\\\"Mpi\\\":{\\\"ProcessCountPerNode\\\":1},\\\"PyTorch\\\":{\\\"CommunicationBackend\\\":\\\"nccl\\\",\\\"ProcessCount\\\":null},\\\"Hdi\\\":{\\\"YarnDeployMode\\\":2},\\\"ContainerInstance\\\":{\\\"Region\\\":null,\\\"CpuCores\\\":2.0,\\\"MemoryGb\\\":3.5},\\\"ExposedPorts\\\":null,\\\"Docker\\\":{\\\"UseDocker\\\":false,\\\"SharedVolumes\\\":true,\\\"ShmSize\\\":\\\"2g\\\",\\\"Arguments\\\":[]},\\\"Cmk8sCompute\\\":{\\\"Configuration\\\":{}},\\\"CommandReturnCodeConfig\\\":{\\\"ReturnCode\\\":0,\\\"SuccessfulReturnCodes\\\":[]},\\\"EnvironmentVariables\\\":{},\\\"ApplicationEndpoints\\\":{},\\\"Parameters\\\":[]},\\\"SnapshotId\\\":\\\"77ac8209-5aa9-499d-9256-12cf909d486a\\\",\\\"Snapshots\\\":[],\\\"SourceCodeDataReference\\\":null,\\\"ParentRunId\\\":null,\\\"DataContainerId\\\":null,\\\"RunType\\\":null,\\\"DisplayName\\\":null,\\\"EnvironmentAssetId\\\":null,\\\"Properties\\\":{},\\\"Tags\\\":{},\\\"AggregatedArtifactPath\\\":null},\\\"ParentRunId\\\":\\\"HD_2695e6d6-fb22-4f99-b257-cd1444ecb878\\\"}\", \"_aml_system_resume_child_runs\": \"null\", \"_aml_system_all_jobs_generated\": \"true\", \"_aml_system_cancellation_requested\": \"true\", \"_aml_system_samples_generated_count\": \"8\", \"_aml_system_progress_metadata_evaluation_timestamp\": \"\\\"2023-09-28T14:49:11.336719\\\"\", \"_aml_system_progress_metadata_digest\": \"\\\"036d4bb4149722795f1761f9b355bec365135edd6b83f6860208fa8d03d1e4d7\\\"\", \"_aml_system_progress_metadata_active_timestamp\": \"\\\"2023-09-28T14:49:11.336719\\\"\", \"_aml_system_optimizer_state_artifact\": \"null\", \"_aml_system_outdated_optimizer_state_artifacts\": \"\\\"[]\\\"\", \"_aml_system_HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_0\": \"{\\\"--C\\\": 500, \\\"--max_iter\\\": 300}\", \"_aml_system_HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_1\": \"{\\\"--C\\\": 500, \\\"--max_iter\\\": 50}\", \"_aml_system_HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_2\": \"{\\\"--C\\\": 0.01, \\\"--max_iter\\\": 100}\", \"_aml_system_HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_3\": \"{\\\"--C\\\": 1, \\\"--max_iter\\\": 50}\", \"_aml_system_HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_4\": \"{\\\"--C\\\": 0.01, \\\"--max_iter\\\": 300}\", \"_aml_system_HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_5\": \"{\\\"--C\\\": 500, \\\"--max_iter\\\": 100}\", \"_aml_system_HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_6\": \"{\\\"--C\\\": 1, \\\"--max_iter\\\": 200}\", \"_aml_system_HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_7\": \"{\\\"--C\\\": 0.1, \\\"--max_iter\\\": 100}\"}, \"script_name\": null, \"arguments\": null, \"end_time_utc\": \"2023-09-28T14:52:11.688491Z\", \"status\": \"Failed\", \"log_files\": {\"azureml-logs/hyperdrive.txt\": \"https://mlstrg241963.blob.core.windows.net/azureml/ExperimentRun/dcid.HD_2695e6d6-fb22-4f99-b257-cd1444ecb878/azureml-logs/hyperdrive.txt?sv=2019-07-07&sr=b&sig=Hl09JRKCfdGb2tytB4qGwV0f7G5yeZaer1WwJ0ZwYYo%3D&skoid=a608fc02-8475-4cfc-a4c7-6e1ca2fef6c1&sktid=660b3398-b80e-49d2-bc5b-ac1dc93b5254&skt=2023-09-28T13%3A39%3A59Z&ske=2023-09-29T21%3A49%3A59Z&sks=b&skv=2019-07-07&st=2023-09-28T14%3A47%3A45Z&se=2023-09-28T22%3A57%3A45Z&sp=r\"}, \"log_groups\": [[\"azureml-logs/hyperdrive.txt\"]], \"run_duration\": \"0:03:31\", \"run_number\": \"1695912520\", \"run_queued_details\": {\"status\": \"Failed\", \"details\": null}, \"hyper_parameters\": {\"--C\": [\"choice\", [[0.01, 0.1, 1, 10, 50, 100, 500, 1000]]], \"--max_iter\": [\"choice\", [[50, 100, 200, 300]]]}}, \"child_runs\": [{\"run_id\": \"HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_0\", \"run_number\": 1695912522, \"metric\": null, \"status\": \"Failed\", \"run_type\": \"azureml.scriptrun\", \"training_percent\": null, \"start_time\": \"2023-09-28T14:48:50.137376Z\", \"end_time\": \"2023-09-28T14:49:24.866208Z\", \"created_time\": \"2023-09-28T14:48:42.838904Z\", \"created_time_dt\": \"2023-09-28T14:48:42.838904Z\", \"duration\": \"0:00:42\", \"hyperdrive_id\": \"2695e6d6-fb22-4f99-b257-cd1444ecb878\", \"arguments\": null, \"param_--C\": 500, \"param_--max_iter\": 300}, {\"run_id\": \"HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_4\", \"run_number\": 1695912612, \"metric\": null, \"status\": \"Failed\", \"run_type\": \"azureml.scriptrun\", \"training_percent\": null, \"start_time\": \"2023-09-28T14:50:21.570302Z\", \"end_time\": \"2023-09-28T14:50:55.18829Z\", \"created_time\": \"2023-09-28T14:50:12.284546Z\", \"created_time_dt\": \"2023-09-28T14:50:12.284546Z\", \"duration\": \"0:00:42\", \"hyperdrive_id\": \"2695e6d6-fb22-4f99-b257-cd1444ecb878\", \"arguments\": null, \"param_--C\": 0.01, \"param_--max_iter\": 300}, {\"run_id\": \"HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_7\", \"run_number\": 1695912642, \"metric\": null, \"status\": \"Failed\", \"run_type\": \"azureml.scriptrun\", \"training_percent\": null, \"start_time\": \"2023-09-28T14:50:58.447253Z\", \"end_time\": \"2023-09-28T14:51:33.475517Z\", \"created_time\": \"2023-09-28T14:50:42.944771Z\", \"created_time_dt\": \"2023-09-28T14:50:42.944771Z\", \"duration\": \"0:00:50\", \"hyperdrive_id\": \"2695e6d6-fb22-4f99-b257-cd1444ecb878\", \"arguments\": null, \"param_--C\": 0.1, \"param_--max_iter\": 100}], \"children_metrics\": {\"categories\": null, \"series\": null, \"metricName\": null}, \"run_metrics\": [], \"run_logs\": \"[2023-09-28T14:48:41.593024][GENERATOR][INFO]Trying to sample '4' jobs from the hyperparameter space\\n[2023-09-28T14:48:42.1465911Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_0' \\n[2023-09-28T14:48:42.2930914Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_1' \\n[2023-09-28T14:48:42.3831550Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_2' \\n[2023-09-28T14:48:42.4609320Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_3' \\n[2023-09-28T14:48:42.419377][GENERATOR][INFO]Successfully sampled '4' jobs, they will soon be submitted to the execution target.\\n[2023-09-28T14:48:42.9043472Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_0' \\n[2023-09-28T14:48:43.0249410Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_3' \\n[2023-09-28T14:48:43.0275114Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_2' \\n[2023-09-28T14:48:43.0251947Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_1' \\n[2023-09-28T14:50:11.724719][GENERATOR][INFO]Trying to sample '2' jobs from the hyperparameter space\\n[2023-09-28T14:50:12.0694289Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_4' \\n[2023-09-28T14:50:12.140208][GENERATOR][INFO]Successfully sampled '2' jobs, they will soon be submitted to the execution target.\\n[2023-09-28T14:50:12.3066145Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_5' \\n[2023-09-28T14:50:12.3740651Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_4' \\n[2023-09-28T14:50:12.5791573Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_5' \\n[2023-09-28T14:50:40.381444][CONTROLLER][WARNING][HDFlowDebug]The first 4 jobs have failed due to usererror. The system is cancelling the further child runs and failing the experiment. Please resolve the issues before resubmitting the experiment.\\n[2023-09-28T14:50:40.381388][CONTROLLER][INFO]Experiment has been marked for cancellation.\\n[2023-09-28T14:50:42.210074][GENERATOR][INFO]Trying to sample '2' jobs from the hyperparameter space\\n[2023-09-28T14:50:42.7606239Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_7' \\n[2023-09-28T14:50:42.6677628Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_6' \\n[2023-09-28T14:50:42.737176][GENERATOR][INFO]Successfully sampled '2' jobs, they will soon be submitted to the execution target.\\n[2023-09-28T14:50:42.9540989Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_6' \\n[2023-09-28T14:50:43.0330111Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_7' \\n[2023-09-28T14:52:10.507196][CONTROLLER][WARNING]Marking the experiment for user error because initial child jobs have failed due to user error\\n[2023-09-28T14:52:10.823964][CONTROLLER][WARNING]Marking the experiment for user error because initial child jobs have failed due to user error\\n[2023-09-28T14:52:10.823912][CONTROLLER][INFO]Experiment has been marked for failure.\\n[2023-09-28T14:52:11.211883][CONTROLLER][INFO]Experiment has been marked for failure.\\n[2023-09-28T14:52:11.211944][CONTROLLER][WARNING]User errors were found in at least one of the child runs.\\n[2023-09-28T14:52:12.161488][CONTROLLER][INFO]Experiment was 'ExperimentStatus.RUNNING', is 'ExperimentStatus.FAILED'.\\n\\nError occurred: Execution failed. User process '/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:     infer_column_types or _is_inference_required(set_column_types))\\n  File \\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_factory.py\\\", line 1173, in _transform_and_validate\\n    _validate_has_data(dataflow, 'Failed to validate the data.')\\n  File \\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_error_handling.py\\\", line 68, in _validate_has_data\\n    raise DatasetValidationError(error_message + '\\\\n' + e.compliant_message, exception=e)\\nazureml.data.dataset_error_handling.DatasetValidationError: DatasetValidationError:\\n\\tMessage: Failed to validate the data.\\nScriptExecutionException was caused by StreamAccessException.\\n  StreamAccessException was caused by NotFoundException.\\n    Found no resources for the input provided: '[REDACTED]'\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\n\\tInnerException None\\n\\tErrorResponse \\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"Failed to validate the data.\\\\nScriptExecutionException was caused by StreamAccessException.\\\\n  StreamAccessException was caused by NotFoundException.\\\\n    Found no resources for the input provided: '[REDACTED]'\\\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\\"\\n    }\\n}\\n\\n Marking the experiment as failed because initial child jobs have failed due to user error\\n\", \"graph\": {}, \"widget_settings\": {\"childWidgetDisplay\": \"popup\", \"send_telemetry\": false, \"log_level\": \"INFO\", \"sdk_version\": \"1.51.0\"}, \"loading\": false}"
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "RunId: HD_2695e6d6-fb22-4f99-b257-cd1444ecb878\n",
      "Web View: https://ml.azure.com/runs/HD_2695e6d6-fb22-4f99-b257-cd1444ecb878?wsid=/subscriptions/61c5c3f0-6dc7-4ed9-a7f3-c704b20e3b30/resourcegroups/aml-quickstarts-241963/workspaces/quick-starts-ws-241963&tid=660b3398-b80e-49d2-bc5b-ac1dc93b5254\n",
      "\n",
      "Streaming azureml-logs/hyperdrive.txt\n",
      "=====================================\n",
      "\n",
      "[2023-09-28T14:48:41.593024][GENERATOR][INFO]Trying to sample '4' jobs from the hyperparameter space\n",
      "[2023-09-28T14:48:42.1465911Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_0' \n",
      "[2023-09-28T14:48:42.2930914Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_1' \n",
      "[2023-09-28T14:48:42.3831550Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_2' \n",
      "[2023-09-28T14:48:42.4609320Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_3' \n",
      "[2023-09-28T14:48:42.419377][GENERATOR][INFO]Successfully sampled '4' jobs, they will soon be submitted to the execution target.\n",
      "[2023-09-28T14:48:42.9043472Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_0' \n",
      "[2023-09-28T14:48:43.0249410Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_3' \n",
      "[2023-09-28T14:48:43.0275114Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_2' \n",
      "[2023-09-28T14:48:43.0251947Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_1' \n",
      "[2023-09-28T14:50:11.724719][GENERATOR][INFO]Trying to sample '2' jobs from the hyperparameter space\n",
      "[2023-09-28T14:50:12.0694289Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_4' \n",
      "[2023-09-28T14:50:12.140208][GENERATOR][INFO]Successfully sampled '2' jobs, they will soon be submitted to the execution target.\n",
      "[2023-09-28T14:50:12.3066145Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_5' \n",
      "[2023-09-28T14:50:12.3740651Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_4' \n",
      "[2023-09-28T14:50:12.5791573Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_5' \n",
      "[2023-09-28T14:50:40.381444][CONTROLLER][WARNING][HDFlowDebug]The first 4 jobs have failed due to usererror. The system is cancelling the further child runs and failing the experiment. Please resolve the issues before resubmitting the experiment.\n",
      "[2023-09-28T14:50:40.381388][CONTROLLER][INFO]Experiment has been marked for cancellation.\n",
      "[2023-09-28T14:50:42.210074][GENERATOR][INFO]Trying to sample '2' jobs from the hyperparameter space\n",
      "[2023-09-28T14:50:42.7606239Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_7' \n",
      "[2023-09-28T14:50:42.6677628Z][SCHEDULER][INFO]Scheduling job, id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_6' \n",
      "[2023-09-28T14:50:42.737176][GENERATOR][INFO]Successfully sampled '2' jobs, they will soon be submitted to the execution target.\n",
      "[2023-09-28T14:50:42.9540989Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_6' \n",
      "[2023-09-28T14:50:43.0330111Z][SCHEDULER][INFO]Successfully scheduled a job. Id='HD_2695e6d6-fb22-4f99-b257-cd1444ecb878_7' \n",
      "[2023-09-28T14:52:10.507196][CONTROLLER][WARNING]Marking the experiment for user error because initial child jobs have failed due to user error\n",
      "[2023-09-28T14:52:10.823964][CONTROLLER][WARNING]Marking the experiment for user error because initial child jobs have failed due to user error\n",
      "[2023-09-28T14:52:10.823912][CONTROLLER][INFO]Experiment has been marked for failure.\n",
      "[2023-09-28T14:52:11.211883][CONTROLLER][INFO]Experiment has been marked for failure.\n",
      "[2023-09-28T14:52:11.211944][CONTROLLER][WARNING]User errors were found in at least one of the child runs.\n",
      "[2023-09-28T14:52:12.161488][CONTROLLER][INFO]Experiment was 'ExperimentStatus.RUNNING', is 'ExperimentStatus.FAILED'.\n",
      "\n",
      "Execution Summary\n",
      "=================\n",
      "RunId: HD_2695e6d6-fb22-4f99-b257-cd1444ecb878\n",
      "Web View: https://ml.azure.com/runs/HD_2695e6d6-fb22-4f99-b257-cd1444ecb878?wsid=/subscriptions/61c5c3f0-6dc7-4ed9-a7f3-c704b20e3b30/resourcegroups/aml-quickstarts-241963/workspaces/quick-starts-ws-241963&tid=660b3398-b80e-49d2-bc5b-ac1dc93b5254\n",
      "\n",
      "Warnings:\n",
      "Execution failed. User process '/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:     infer_column_types or _is_inference_required(set_column_types))\n",
      "  File \"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_factory.py\", line 1173, in _transform_and_validate\n",
      "    _validate_has_data(dataflow, 'Failed to validate the data.')\n",
      "  File\n",
      "Execution failed. User process '/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:     infer_column_types or _is_inference_required(set_column_types))\n",
      "  File \"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_factory.py\", line 1173, in _transform_and_validate\n",
      "    _validate_has_data(dataflow, 'Failed to validate the data.')\n",
      "  File\n",
      "\n"
     ]
    },
    {
     "ename": "ActivityFailedException",
     "evalue": "ActivityFailedException:\n\tMessage: Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"Execution failed. User process '/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:     infer_column_types or _is_inference_required(set_column_types))\\n  File \\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_factory.py\\\", line 1173, in _transform_and_validate\\n    _validate_has_data(dataflow, 'Failed to validate the data.')\\n  File \\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_error_handling.py\\\", line 68, in _validate_has_data\\n    raise DatasetValidationError(error_message + '\\\\n' + e.compliant_message, exception=e)\\nazureml.data.dataset_error_handling.DatasetValidationError: DatasetValidationError:\\n\\tMessage: Failed to validate the data.\\nScriptExecutionException was caused by StreamAccessException.\\n  StreamAccessException was caused by NotFoundException.\\n    Found no resources for the input provided: '[REDACTED]'\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\n\\tInnerException None\\n\\tErrorResponse \\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"Failed to validate the data.\\\\nScriptExecutionException was caused by StreamAccessException.\\\\n  StreamAccessException was caused by NotFoundException.\\\\n    Found no resources for the input provided: '[REDACTED]'\\\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\\"\\n    }\\n}\\n\\n Marking the experiment as failed because initial child jobs have failed due to user error\",\n        \"messageParameters\": {},\n        \"details\": []\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"Activity Failed:\\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"Execution failed. User process '/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:     infer_column_types or _is_inference_required(set_column_types))\\\\n  File \\\\\\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_factory.py\\\\\\\", line 1173, in _transform_and_validate\\\\n    _validate_has_data(dataflow, 'Failed to validate the data.')\\\\n  File \\\\\\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_error_handling.py\\\\\\\", line 68, in _validate_has_data\\\\n    raise DatasetValidationError(error_message + '\\\\\\\\n' + e.compliant_message, exception=e)\\\\nazureml.data.dataset_error_handling.DatasetValidationError: DatasetValidationError:\\\\n\\\\tMessage: Failed to validate the data.\\\\nScriptExecutionException was caused by StreamAccessException.\\\\n  StreamAccessException was caused by NotFoundException.\\\\n    Found no resources for the input provided: '[REDACTED]'\\\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\\\n\\\\tInnerException None\\\\n\\\\tErrorResponse \\\\n{\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"Failed to validate the data.\\\\\\\\nScriptExecutionException was caused by StreamAccessException.\\\\\\\\n  StreamAccessException was caused by NotFoundException.\\\\\\\\n    Found no resources for the input provided: '[REDACTED]'\\\\\\\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\\\\\\"\\\\n    }\\\\n}\\\\n\\\\n Marking the experiment as failed because initial child jobs have failed due to user error\\\",\\n        \\\"messageParameters\\\": {},\\n        \\\"details\\\": []\\n    },\\n    \\\"time\\\": \\\"0001-01-01T00:00:00.000Z\\\"\\n}\"\n    }\n}",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mActivityFailedException\u001b[0m                   Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[26], line 7\u001b[0m\n\u001b[1;32m      4\u001b[0m RunDetails(hyperdrive_run)\u001b[38;5;241m.\u001b[39mshow()\n\u001b[1;32m      6\u001b[0m hyperdrive_run\u001b[38;5;241m.\u001b[39mget_status()\n\u001b[0;32m----> 7\u001b[0m \u001b[43mhyperdrive_run\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait_for_completion\u001b[49m\u001b[43m(\u001b[49m\u001b[43mshow_output\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/core/run.py:849\u001b[0m, in \u001b[0;36mRun.wait_for_completion\u001b[0;34m(self, show_output, wait_post_processing, raise_on_error)\u001b[0m\n\u001b[1;32m    847\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m show_output:\n\u001b[1;32m    848\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 849\u001b[0m         \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_stream_run_output\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    850\u001b[0m \u001b[43m            \u001b[49m\u001b[43mfile_handle\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msys\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstdout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    851\u001b[0m \u001b[43m            \u001b[49m\u001b[43mwait_post_processing\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mwait_post_processing\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    852\u001b[0m \u001b[43m            \u001b[49m\u001b[43mraise_on_error\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mraise_on_error\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    853\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mget_details()\n\u001b[1;32m    854\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyboardInterrupt\u001b[39;00m:\n",
      "File \u001b[0;32m/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/core/run.py:1102\u001b[0m, in \u001b[0;36mRun._stream_run_output\u001b[0;34m(self, file_handle, wait_post_processing, raise_on_error)\u001b[0m\n\u001b[1;32m   1100\u001b[0m         file_handle\u001b[38;5;241m.\u001b[39mwrite(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m   1101\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m-> 1102\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m ActivityFailedException(error_details\u001b[38;5;241m=\u001b[39mjson\u001b[38;5;241m.\u001b[39mdumps(error, indent\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m4\u001b[39m))\n\u001b[1;32m   1104\u001b[0m file_handle\u001b[38;5;241m.\u001b[39mwrite(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m   1105\u001b[0m file_handle\u001b[38;5;241m.\u001b[39mflush()\n",
      "\u001b[0;31mActivityFailedException\u001b[0m: ActivityFailedException:\n\tMessage: Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"Execution failed. User process '/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:     infer_column_types or _is_inference_required(set_column_types))\\n  File \\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_factory.py\\\", line 1173, in _transform_and_validate\\n    _validate_has_data(dataflow, 'Failed to validate the data.')\\n  File \\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_error_handling.py\\\", line 68, in _validate_has_data\\n    raise DatasetValidationError(error_message + '\\\\n' + e.compliant_message, exception=e)\\nazureml.data.dataset_error_handling.DatasetValidationError: DatasetValidationError:\\n\\tMessage: Failed to validate the data.\\nScriptExecutionException was caused by StreamAccessException.\\n  StreamAccessException was caused by NotFoundException.\\n    Found no resources for the input provided: '[REDACTED]'\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\n\\tInnerException None\\n\\tErrorResponse \\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"Failed to validate the data.\\\\nScriptExecutionException was caused by StreamAccessException.\\\\n  StreamAccessException was caused by NotFoundException.\\\\n    Found no resources for the input provided: '[REDACTED]'\\\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\\"\\n    }\\n}\\n\\n Marking the experiment as failed because initial child jobs have failed due to user error\",\n        \"messageParameters\": {},\n        \"details\": []\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"Activity Failed:\\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"Execution failed. User process '/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:     infer_column_types or _is_inference_required(set_column_types))\\\\n  File \\\\\\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_factory.py\\\\\\\", line 1173, in _transform_and_validate\\\\n    _validate_has_data(dataflow, 'Failed to validate the data.')\\\\n  File \\\\\\\"/azureml-envs/azureml_7eec2c8971b9410f92147a7e257297e7/lib/python3.6/site-packages/azureml/data/dataset_error_handling.py\\\\\\\", line 68, in _validate_has_data\\\\n    raise DatasetValidationError(error_message + '\\\\\\\\n' + e.compliant_message, exception=e)\\\\nazureml.data.dataset_error_handling.DatasetValidationError: DatasetValidationError:\\\\n\\\\tMessage: Failed to validate the data.\\\\nScriptExecutionException was caused by StreamAccessException.\\\\n  StreamAccessException was caused by NotFoundException.\\\\n    Found no resources for the input provided: '[REDACTED]'\\\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\\\n\\\\tInnerException None\\\\n\\\\tErrorResponse \\\\n{\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"Failed to validate the data.\\\\\\\\nScriptExecutionException was caused by StreamAccessException.\\\\\\\\n  StreamAccessException was caused by NotFoundException.\\\\\\\\n    Found no resources for the input provided: '[REDACTED]'\\\\\\\\n| session_id=l_01f5bafa-fd0f-492f-8525-cf1c33ebea5b\\\\\\\"\\\\n    }\\\\n}\\\\n\\\\n Marking the experiment as failed because initial child jobs have failed due to user error\\\",\\n        \\\"messageParameters\\\": {},\\n        \\\"details\\\": []\\n    },\\n    \\\"time\\\": \\\"0001-01-01T00:00:00.000Z\\\"\\n}\"\n    }\n}"
     ]
    }
   ],
   "source": [
    "# Submit your hyperdrive run to the experiment and show run details with the widget.\n",
    "\n",
    "hyperdrive_run= exp.submit(hyperdrive_config,show_output=True)\n",
    "RunDetails(hyperdrive_run).show()\n",
    "\n",
    "hyperdrive_run.get_status()\n",
    "hyperdrive_run.wait_for_completion(show_output=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "gather": {
     "logged": 1598276310862
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "import joblib\n",
    "# Get your best run and save the model from that run.\n",
    "print(hyperdrive_run.get_children_sorted_by_primary_metric(top=0,reverse =False, discard_no_metric=False))\n",
    "### YOUR CODE HERE ###\n",
    "best_run=hyperdrive_run.get_best_run_by_primary_metric()\n",
    "print(\"Best run metric:\", best_run.get_metrics())\n",
    "print(\"Run details\",best_run.get_details() )\n",
    "print(\"Best run file names\", best_run.get_file_names())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "hypr_mdl='hyperdrive_model'\n",
    "hyperdrive_model=best_run.register_model(model_name=hypr_mdl, model_path='.outputs/model.joblib')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "from azureml.data.dataset_factory import TabularDatasetFactory\n",
    "\n",
    "# Create TabularDataset using TabularDatasetFactory\n",
    "# Data is available at: \n",
    "# \"https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv\"\n",
    "\n",
    "### YOUR CODE HERE ###\n",
    "ds=TabularDatasetFactory.from_delimited_files(['https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "os.getcwd()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.listdir()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "gather": {
     "logged": 1598275726969
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from train import clean_data\n",
    "\n",
    "# Use the clean_data function to clean your data.\n",
    "x, y = clean_data(ds)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "gather": {
     "logged": 1598275665403
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from azureml.train.automl import AutoMLConfig\n",
    "\n",
    "# Set parameters for AutoMLConfig\n",
    "# NOTE: DO NOT CHANGE THE experiment_timeout_minutes PARAMETER OR YOUR INSTANCE WILL TIME OUT.\n",
    "# If you wish to run the experiment longer, you will need to run this notebook in your own\n",
    "# Azure tenant, which will incur personal costs.\n",
    "automl_config = AutoMLConfig(\n",
    "    experiment_timeout_minutes=30,\n",
    "    task='classification',\n",
    "    primary_metric='Accuracy',\n",
    "    training_data=x,\n",
    "    label_column_name=y,\n",
    "    n_cross_validations=5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [
    {
     "ename": "ConfigException",
     "evalue": "ConfigException:\n\tMessage: Argument [label_column_name] is of unsupported type: [<class 'pandas.core.series.Series'>]. Supported type(s): [int, str]\n\tInnerException: None\n\tErrorResponse \n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"Argument [label_column_name] is of unsupported type: [<class 'pandas.core.series.Series'>]. Supported type(s): [int, str]\",\n        \"details_uri\": \"https://aka.ms/AutoMLConfig\",\n        \"target\": \"label_column_name\",\n        \"inner_error\": {\n            \"code\": \"BadArgument\",\n            \"inner_error\": {\n                \"code\": \"ArgumentInvalid\"\n            }\n        },\n        \"reference_code\": \"061ed905-e59e-42b9-ad95-cd18f40b4358\"\n    }\n}",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mConfigException\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[12], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# Submit your automl run\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m run\u001b[38;5;241m=\u001b[39m\u001b[43mexp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msubmit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconfig\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mautoml_config\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mshow_output\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/core/experiment.py:238\u001b[0m, in \u001b[0;36mExperiment.submit\u001b[0;34m(self, config, tags, **kwargs)\u001b[0m\n\u001b[1;32m    236\u001b[0m submit_func \u001b[38;5;241m=\u001b[39m get_experiment_submit(config)\n\u001b[1;32m    237\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_log_context(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msubmit config \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(config\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__class__\u001b[39m\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)):\n\u001b[0;32m--> 238\u001b[0m     run \u001b[38;5;241m=\u001b[39m \u001b[43msubmit_func\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mworkspace\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    239\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m tags \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    240\u001b[0m     run\u001b[38;5;241m.\u001b[39mset_tags(tags)\n",
      "File \u001b[0;32m/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/train/automl/automlconfig.py:95\u001b[0m, in \u001b[0;36m_automl_static_submit\u001b[0;34m(automl_config_object, workspace, experiment_name, **kwargs)\u001b[0m\n\u001b[1;32m     92\u001b[0m run_config \u001b[38;5;241m=\u001b[39m automl_config_object\u001b[38;5;241m.\u001b[39m_run_configuration\n\u001b[1;32m     93\u001b[0m compute_target \u001b[38;5;241m=\u001b[39m automl_config_object\u001b[38;5;241m.\u001b[39muser_settings\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcompute_target\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m---> 95\u001b[0m \u001b[43mautoml_config_object\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_validate_config_settings\u001b[49m\u001b[43m(\u001b[49m\u001b[43mworkspace\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     96\u001b[0m fit_params \u001b[38;5;241m=\u001b[39m automl_config_object\u001b[38;5;241m.\u001b[39m_get_fit_params()\n\u001b[1;32m     98\u001b[0m \u001b[38;5;66;03m# retrieve settings which are present in user but not part of fit_params\u001b[39;00m\n",
      "File \u001b[0;32m/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/train/automl/automlconfig.py:2229\u001b[0m, in \u001b[0;36mAutoMLConfig._validate_config_settings\u001b[0;34m(self, workspace)\u001b[0m\n\u001b[1;32m   2225\u001b[0m     \u001b[38;5;66;03m# todo is there a scenario where we are accessing the label column via an integer index?\u001b[39;00m\n\u001b[1;32m   2226\u001b[0m     \u001b[38;5;66;03m# if not, the following should only check for string\u001b[39;00m\n\u001b[1;32m   2227\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m ((\u001b[38;5;28misinstance\u001b[39m(label_column_name_val, \u001b[38;5;28mint\u001b[39m) \u001b[38;5;129;01mand\u001b[39;00m has_training_input_pandas_obj)\n\u001b[1;32m   2228\u001b[0m             \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(label_column_name_val, \u001b[38;5;28mstr\u001b[39m)):\n\u001b[0;32m-> 2229\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m ConfigException\u001b[38;5;241m.\u001b[39m_with_error(\n\u001b[1;32m   2230\u001b[0m             AzureMLError\u001b[38;5;241m.\u001b[39mcreate(\n\u001b[1;32m   2231\u001b[0m                 InvalidArgumentType, target\u001b[38;5;241m=\u001b[39mlabel_column_name_param_name,\n\u001b[1;32m   2232\u001b[0m                 argument\u001b[38;5;241m=\u001b[39mlabel_column_name_param_name, actual_type\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mtype\u001b[39m(label_column_name_val),\n\u001b[1;32m   2233\u001b[0m                 expected_types\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m, \u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mjoin([\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mint\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mstr\u001b[39m\u001b[38;5;124m\"\u001b[39m]),\n\u001b[1;32m   2234\u001b[0m                 reference_code\u001b[38;5;241m=\u001b[39mReferenceCodes\u001b[38;5;241m.\u001b[39m_AUTOML_CONFIG_LABEL_COL_NAME_WRONG_TYPE\n\u001b[1;32m   2235\u001b[0m             )\n\u001b[1;32m   2236\u001b[0m         )\n\u001b[1;32m   2237\u001b[0m \u001b[38;5;66;03m# Weight Column Name\u001b[39;00m\n\u001b[1;32m   2238\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39muser_settings\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mweight_column_name\u001b[39m\u001b[38;5;124m'\u001b[39m) \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mConfigException\u001b[0m: ConfigException:\n\tMessage: Argument [label_column_name] is of unsupported type: [<class 'pandas.core.series.Series'>]. Supported type(s): [int, str]\n\tInnerException: None\n\tErrorResponse \n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"Argument [label_column_name] is of unsupported type: [<class 'pandas.core.series.Series'>]. Supported type(s): [int, str]\",\n        \"details_uri\": \"https://aka.ms/AutoMLConfig\",\n        \"target\": \"label_column_name\",\n        \"inner_error\": {\n            \"code\": \"BadArgument\",\n            \"inner_error\": {\n                \"code\": \"ArgumentInvalid\"\n            }\n        },\n        \"reference_code\": \"061ed905-e59e-42b9-ad95-cd18f40b4358\"\n    }\n}"
     ]
    }
   ],
   "source": [
    "# Submit your automl run\n",
    "run=exp.submit(config=automl_config, show_output=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Retrieve and save your best automl model.\n",
    "\n",
    "best_run, fitted_model=run.get_output()\n",
    "print(best_run)\n",
    "print(fitted_model)\n",
    "\n",
    "print(\"Best run metrics :\", best_run.get_metrics())\n",
    "print(\"Best run details :\", best_run.get_details())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernel_info": {
   "name": "python3-azureml"
  },
  "kernelspec": {
   "display_name": "Python 3.8 - AzureML",
   "language": "python",
   "name": "python38-azureml"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  },
  "nteract": {
   "version": "nteract-front-end@1.0.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
